# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
### Use node:lts-alpine as the base image
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy the rest of the application files
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose any ports if needed (MCP uses stdio so not needed) 

# Command to run the MCP server
CMD [ "node", "dist/index.js" ]
